server:
  port: 8080

spring:
  application:
    name: ECMS
  datasource:
    url: jdbc:postgresql://localhost:5432/ecms_db
    username: ecms_user
    password: ecms_pwd
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true